/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class EsoLocal */

#ifndef _Included_EsoLocal
#define _Included_EsoLocal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     EsoLocal
 * Method:    pingEsoLocal
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_EsoLocal_pingEsoLocal
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
