/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class EsoLocal_EsoLocal_Hash */

#ifndef _Included_EsoLocal_EsoLocal_Hash
#define _Included_EsoLocal_EsoLocal_Hash
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
