/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class EsoLocal_EsoLocal */

#ifndef _Included_EsoLocal_EsoLocal
#define _Included_EsoLocal_EsoLocal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     EsoLocal_EsoLocal
 * Method:    pingEsoLocal
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_EsoLocal_EsoLocal_pingEsoLocal
  (JNIEnv *, jobject);

/*
 * Class:     EsoLocal_EsoLocal
 * Method:    encrypt
 * Signature: (Ljava/lang/String;I[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_EsoLocal_EsoLocal_encrypt
  (JNIEnv *, jobject, jstring, jint, jbyteArray);

/*
 * Class:     EsoLocal_EsoLocal
 * Method:    decrypt
 * Signature: (Ljava/lang/String;I[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_EsoLocal_EsoLocal_decrypt
  (JNIEnv *, jobject, jstring, jint, jbyteArray);

/*
 * Class:     EsoLocal_EsoLocal
 * Method:    hmac
 * Signature: (Ljava/lang/String;I[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_EsoLocal_EsoLocal_hmac
  (JNIEnv *, jobject, jstring, jint, jbyteArray, jint);

/*
 * Class:     EsoLocal_EsoLocal
 * Method:    sign
 * Signature: (Ljava/lang/String;I[BI)[B
 */
JNIEXPORT jbyteArray JNICALL Java_EsoLocal_EsoLocal_sign
  (JNIEnv *, jobject, jstring, jint, jbyteArray, jint);

/*
 * Class:     EsoLocal_EsoLocal
 * Method:    verify
 * Signature: (Ljava/lang/String;I[B[BI)Z
 */
JNIEXPORT jboolean JNICALL Java_EsoLocal_EsoLocal_verify
  (JNIEnv *, jobject, jstring, jint, jbyteArray, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
